#!/bin/bash
short=$(hostname -s)
sym="s4"
size="small"
echo "Maris Cluster: Starting $sym $size" | mail -s "Maris Cluster: $short" joskodeboer@gmail.com
./calculation $sym $size >>  "${short}_data_${sym}_${size}.txt"
echo "Maris Cluster: Finished $sym $size" | mailx -a ${short}_data_c2v_small.txt -s "Maris Cluster: $short" joskodeboer@gmail.com
