#!/bin/bash
short=$(hostname -s)
sym="d2d"
size="large"
echo "Maris Cluster: Starting  Finite K $sym $size" | mail -s "Maris Cluster Finite K: $short" joskodeboer@gmail.com
./calculation $sym $size >>  "${short}_data_${sym}_${size}.txt"
echo "Maris Cluster: Finished  Finite K $sym $size" | mailx -a ${short}_data_c2v_small.txt -s "Maris Cluster  Finite K: $short" joskodeboer@gmail.com