#!/bin/bash 

g++ -O3 -g -fno-strict-aliasing -std=c++11 -Wall -Wextra -msse2 -DHAVE_SSE2=1  -DDSFMT_MEXP=19937 -o calculation  simulation_parallel.cpp dSFMT*/dSFMT.c simulation.cpp data.cpp symmetryctwo.cpp symmetryctwoh.cpp symmetryctwov.cpp symmetrydtwod.cpp symmetrydtwoh.cpp symmetrystwo.cpp symmetrysfour.cpp -lgsl -lgslcblas -lm -fopenmp -lpthread 
echo "Running program:"


echo "Maris Cluster: Starting d2d test" | mail -s "Maris Cluster" joskodeboer@gmail.com
rm test.txt
./calculation d2d test >> test.txt
echo "Maris Cluster: Finished d2d test" | mailx -a test.txt -s "Maris Cluster" joskodeboer@gmail.com

