#!/bin/bash 

ulimit -s 65536
g++ -g -O3 -fno-strict-aliasing -std=c++11 -Wall -Wextra -msse2 -DHAVE_SSE2=1  -DDSFMT_MEXP=19937 -o calc_three  simulation_jthree.cpp dSFMT*/dSFMT.c order_dummy.cpp order_d2d.cpp  order_d4h.cpp order_d4h_2.cpp simulation.cpp data.cpp symmetryctwo.cpp symmetryctwoh.cpp symmetryctwov.cpp symmetrydtwod.cpp symmetrydtwoh.cpp symmetrystwo.cpp symmetrysfour.cpp -lgsl -lgslcblas -lm -fopenmp -lpthread 

./calc_three d2d tiny
echo "End compilation (remove exit for cluster)."
exit;
short=$(hostname -s)
sym="d2d"
size="large"
echo "Maris Cluster: Starting $sym $size" | mail -s "Maris Cluster: $short" joskodeboer@gmail.com
./calc_three $sym $size >>  "${short}_data_${sym}_${size}.txt"
echo "Maris Cluster: Finished $sym $size" | mailx -a ${short}_data_c2v_small.txt -s "Maris Cluster: $short" joskodeboer@gmail.com