#!/bin/bash 

ulimit -s 65536
g++ -g -O3 -fno-strict-aliasing -std=c++11 -Wall -Wextra -msse2 -DHAVE_SSE2=1  -DDSFMT_MEXP=19937 -o calc_vis  visualisation.cpp dSFMT*/dSFMT.c simulation.cpp data.cpp symmetrydtwod.cpp -lgsl -lgslcblas -lm -fopenmp -lpthread 
 
./calc_vis