#!/bin/bash 

for i in {0..20}
do 
        python get_data.py -f rough_sweep.txt -n $i >> figure_data.dat 
        gnuplot figure.plt
        mv figure_data.png figure_rough_$i.png
        mv figure_data.dat figure_rough_$i.dat 
        mv figure_rough_$i.* test_4        
done



for i in {0..20}
do 
        python get_data.py -f fine_sweep.txt -n $i >> figure_data.dat 
        gnuplot figure.plt
        mv figure_data.png figure_fine_$i.png
        mv figure_data.dat figure_fine_$i.dat 
        mv figure_fine_$i.* test_4        
done
