#!/bin/bash 
rm *.txt

echo "Maris Cluster: Starting c2 test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2 test >> data_c2_test.txt
echo "Maris Cluster: Finished c2 test" | mailx -a data_c2_test.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  c2v test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2v test >> data_c2v_test.txt
echo "Maris Cluster: Finished  c2v test" | mailx -a data_c2v_test.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting c2h test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2h test >> data_c2h_test.txt
echo "Maris Cluster: Finished c2h test" | mailx -a data_c2h_test.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  d2d test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation d2d test >> data_d2d_test.txt
echo "Maris Cluster: Finished  d2d test" | mailx -a data_d2d_test.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  d2h test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation d2h test >> data_d2h_test.txt
echo "Maris Cluster: Finished d2h test" | mailx -a data_d2h_test.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  s2 test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation s2 test >> data_s2_test.txt
echo "Maris Cluster: Finished  s2 test" | mailx -a data_s2_test.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  test" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation s4 test >> data_s4_test.txt
echo "Maris Cluster: Finished  s4 test" | mailx -a data_s4_test.txt -s "Maris Cluster" joskodeboer@gmail.com




echo "Maris Cluster: Starting c2 small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2 small >> data_c2_small.txt
echo "Maris Cluster: Finished c2 small" | mailx -a data_c2_small.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  c2v small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2v small >> data_c2v_small.txt
echo "Maris Cluster: Finished  c2v small" | mailx -a data_c2v_small.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting c2h small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2h small >> data_c2h_small.txt
echo "Maris Cluster: Finished c2h small" | mailx -a data_c2h_small.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  d2d small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation d2d small >> data_d2d_small.txt
echo "Maris Cluster: Finished  d2d small" | mailx -a data_d2d_small.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  d2h small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation d2h small >> data_d2h_small.txt
echo "Maris Cluster: Finished d2h small" | mailx -a data_d2h_small.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  s2 small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation s2 small >> data_s2_small.txt
echo "Maris Cluster: Finished  s2 small" | mailx -a data_s2_small.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting  small" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation s4 small >> data_s4_small.txt
echo "Maris Cluster: Finished  s4 small" | mailx -a data_s4_small.txt -s "Maris Cluster" joskodeboer@gmail.com


echo "Maris Cluster: Starting c2 large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2 large >> data_c2_large.txt
echo "Maris Cluster: Finished c2 large" | mailx -a data_c2_large.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting c2v large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2v large >> data_c2v_large.txt
echo "Maris Cluster: Finished c2v large" | mailx -a data_c2v_large.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting c2h large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation c2h large >> data_c2h_large.txt
echo "Maris Cluster: Finished c2h large" | mailx -a data_c2h_large.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting d2d large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation d2d large >> data_d2d_large.txt
echo "Maris Cluster: Finished d2d large" | mailx -a data_d2d_large.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting d2h large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation d2h large >> data_d2h_large.txt
echo "Maris Cluster: Finished d2h large" | mailx -a data_d2h_large.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting s2 large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation s2 large >> data_s2_large.txt
echo "Maris Cluster: Finished s2 large" | mailx -a data_s2_large.txt -s "Maris Cluster" joskodeboer@gmail.com

echo "Maris Cluster: Starting s4 large" | mail -s "Maris Cluster" joskodeboer@gmail.com
./calculation s4 large >> data_s4_large.txt
echo "Maris Cluster: Finished s4 large" | mailx -a data_s4_large.txt -s "Maris Cluster" joskodeboer@gmail.com

mkdir results_0
mv *.txt results_0
git add results_0 results_0/*

echo "Maris Cluster: Finished Job. Please login and upload results." | mail -s "Maris Cluster" joskodeboer@gmail.com
